### ISSUE TITLE
Question: Is it possible to decode an encoded image inside a screenshot

### ISSUE THREAD

**Issue by samuelbeek** [isena/ISStego#2]
If I take a screenshot of an encoded image, can I decode it? It doesn't seem to work now, but I feel it must be possible since iPhone screenshots are loseless.

**Comment by isena** [comment]
Hi Samuel,

If your generated image is lossless and it has the SAME size (weight x height) of the original image, I believe that you can decode. 

You can use 'compare' tool to an image diff and see if you really have an equivalent image.

**Comment by samuelbeek** [comment]
Thanks @isena I will do some experiments and let you know what my findings are.
